//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace CarServiceAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int AutoId { get; set; }

        [RegularExpression(@"((\w){2}\s(\d){3}\s(\w){3})|((\w){2}(\d){8})")]
        public string NumarAuto { get; set; }
        public string SerieSasiu { get; set; }
        public int ClientClientId { get; set; }
    
        public virtual Sasiu Sasiu { get; set; }
    }
}
