//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Remoting.Messaging;
using System.Runtime.Serialization;

namespace CarServiceAPI.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
	[DataContract(IsReference = true)]
    public partial class Auto
    {
		[DataMember]
        public int AutoId { get; set; }

		[DataMember]
        [RegularExpression(@"((\w){2}\s(\d){3}\s(\w){3})|((\w){2}(\d){8})")]
        public string NumarAuto { get; set; }

		[DataMember]
        public string SerieSasiu { get; set; }
        
		[DataMember]
		public virtual Client Client { get; set; }
    
		[DataMember]
        public virtual Sasiu Sasiu { get; set; }

        public Auto()
        {
            // EF
        }

        public Auto(string numarAuto, string serieSasiu, Client client, Sasiu sasiu)
        {
            NumarAuto = numarAuto ?? throw new ArgumentNullException(nameof(numarAuto));
            SerieSasiu = serieSasiu ?? throw new ArgumentNullException(nameof(serieSasiu));
            Client = client ?? throw new ArgumentNullException(nameof(client));
            Sasiu = sasiu ?? throw new ArgumentNullException(nameof(sasiu));
        }

        public override string ToString()
        {
            return NumarAuto;
        }
    }
}
