//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int ComandaId { get; set; }
        public Stare StareComanda { get; set; }
        public System.DateTime DataSystem { get; set; }
        public System.DateTime DataProgramare { get; set; }
        public System.DateTime DataFinalizare { get; set; }
        public int KmBord { get; set; }
        public string Descriere { get; set; }
        public decimal ValoarePiese { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Client Client { get; set; }

        public Comanda()
        {
            // EF
        }

        public Comanda(Stare stare, DateTime dataSystem, DateTime dataProgramare, DateTime dataFinalizare, int kmBord, 
            string descriere, decimal valoarePiese, Auto auto, Client client)
        {
            StareComanda = stare;
            DataSystem = dataSystem;
            DataProgramare = dataProgramare;
            DataFinalizare = dataFinalizare;
            KmBord = kmBord;
            Descriere = descriere ?? throw new ArgumentNullException(nameof(descriere));
            ValoarePiese = valoarePiese;
            Auto = auto ?? throw new ArgumentNullException(nameof(auto));
            Client = client ?? throw new ArgumentNullException(nameof(client));
        }

        public override string ToString()
        {
            return ComandaId + ", " + Auto + ", " + Client;
        }
    }
}
