//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagine
    {
        public int ImagineId { get; private set; }
        public string Titlu { get; private set; }
        public string Descriere { get; private set; }
        public System.DateTime Data { get; private set; }
        public byte[] Foto { get; private set; }

        public Imagine()
        {
            // EF
        }

        public Imagine(string titlu, string descriere, DateTime data, byte[] foto)
        {
            Titlu = titlu ?? throw new ArgumentNullException(nameof(titlu));
            Descriere = descriere ?? throw new ArgumentNullException(nameof(descriere));
            Data = data;
            Foto = foto ?? throw new ArgumentNullException(nameof(foto));
        }

        public override string ToString()
        {
            return Titlu;
        }
    }
}
