//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAPI.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Imagine
    {
		[DataMember]
        public int ImagineId { get; set; }
        
		[DataMember]
		public string Titlu { get; set; }
        
		[DataMember]
		public string Descriere { get; set; }
        
		[DataMember]
		public System.DateTime Data { get; set; }
        
		[DataMember]
		public byte[] Foto { get; set; }
    
        [DataMember]
		public virtual DetaliuComanda DetaliuComanda { get; set; }

        public Imagine()
        {
            // EF
        }

        public Imagine(string titlu, string descriere, DateTime data, byte[] foto, DetaliuComanda detaliuComanda)
        {
            Titlu = titlu ?? throw new ArgumentNullException(nameof(titlu));
            Descriere = descriere ?? throw new ArgumentNullException(nameof(descriere));
            Data = data;
            Foto = foto ?? throw new ArgumentNullException(nameof(foto));
            DetaliuComanda = detaliuComanda ?? throw new ArgumentNullException(nameof(detaliuComanda));
        }

        public override string ToString()
        {
            return Titlu;
        }
    }
}
