//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAPI.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Material
    {
		[DataMember]
        public int MaterialId { get; set; }
        
		[DataMember]
		public string Denumire { get; set; }
        
		[DataMember]
		public decimal Cantitate { get; set; }
        
		[DataMember]
		public decimal Pret { get; private set; }
        
		[DataMember]
		public System.DateTime DataAprovizionare { get; set; }

        public Material()
        {
            // EF
        }

        public Material(string denumire, decimal cantitate, decimal pret, DateTime data)
        {
            Denumire = denumire ?? throw new ArgumentNullException(nameof(denumire));
            Cantitate = cantitate;
            Pret = pret;
            DataAprovizionare = data;
        }

        public override string ToString()
        {
            return Denumire;
        }
    }
}
