//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAPI.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Mecanic
    {
		[DataMember]
        public int MecanicId { get; set; }
        
		[DataMember]
		public string Nume { get; set; }
        
		[DataMember]
		public string Prenume { get; set; }

        public Mecanic()
        {
            // EF
        }

        public Mecanic(string nume, string prenume)
        {
            Nume = nume ?? throw new ArgumentNullException(nameof(nume));
            Prenume = prenume ?? throw new ArgumentNullException(nameof(prenume));
        }

        public override string ToString()
        {
            return Nume + " " + Prenume;
        }
    }
}
