//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAPI.Model
{
    using System;
    using System.Runtime.Serialization;

    [DataContract]
    public enum Stare : int
    {
        [EnumMember(Value = "inAsteptare")]
        inAsteptare = 0,
        [EnumMember(Value = "executata")]
        executata = 1,
        [EnumMember(Value = "refuzataLaExecutie")]
        refuzataLaExecutie = 2
    }
}
