//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAPI.Model
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdresaField;
        
        private CarServiceAPI.Model.Auto[] AutoesField;
        
        private int ClientIdField;
        
        private string EmailField;
        
        private string JudetField;
        
        private string LocalitateField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private string TelefonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Auto[] Autoes
        {
            get
            {
                return this.AutoesField;
            }
            set
            {
                this.AutoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet
        {
            get
            {
                return this.JudetField;
            }
            set
            {
                this.JudetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate
        {
            get
            {
                return this.LocalitateField;
            }
            set
            {
                this.LocalitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AutoIdField;
        
        private CarServiceAPI.Model.Client ClientField;
        
        private string NumarAutoField;
        
        private CarServiceAPI.Model.Sasiu SasiuField;
        
        private string SerieSasiuField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId
        {
            get
            {
                return this.AutoIdField;
            }
            set
            {
                this.AutoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto
        {
            get
            {
                return this.NumarAutoField;
            }
            set
            {
                this.NumarAutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Sasiu Sasiu
        {
            get
            {
                return this.SasiuField;
            }
            set
            {
                this.SasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu
        {
            get
            {
                return this.SerieSasiuField;
            }
            set
            {
                this.SerieSasiuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodSasiuField;
        
        private string DenumireField;
        
        private int SasiuIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu
        {
            get
            {
                return this.CodSasiuField;
            }
            set
            {
                this.CodSasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId
        {
            get
            {
                return this.SasiuIdField;
            }
            set
            {
                this.SasiuIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Comanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarServiceAPI.Model.Auto AutoField;
        
        private CarServiceAPI.Model.Client ClientField;
        
        private int ComandaIdField;
        
        private System.DateTime DataFinalizareField;
        
        private System.DateTime DataProgramareField;
        
        private System.DateTime DataSystemField;
        
        private string DescriereField;
        
        private int KmBordField;
        
        private CarServiceAPI.Model.Stare StareComandaField;
        
        private decimal ValoarePieseField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Auto Auto
        {
            get
            {
                return this.AutoField;
            }
            set
            {
                this.AutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId
        {
            get
            {
                return this.ComandaIdField;
            }
            set
            {
                this.ComandaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFinalizare
        {
            get
            {
                return this.DataFinalizareField;
            }
            set
            {
                this.DataFinalizareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare
        {
            get
            {
                return this.DataProgramareField;
            }
            set
            {
                this.DataProgramareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem
        {
            get
            {
                return this.DataSystemField;
            }
            set
            {
                this.DataSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KmBord
        {
            get
            {
                return this.KmBordField;
            }
            set
            {
                this.KmBordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Stare StareComanda
        {
            get
            {
                return this.StareComandaField;
            }
            set
            {
                this.StareComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValoarePiese
        {
            get
            {
                return this.ValoarePieseField;
            }
            set
            {
                this.ValoarePieseField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stare", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model")]
    public enum Stare : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        inAsteptare = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        executata = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        refuzataLaExecutie = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Imagine : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DataField;
        
        private string DescriereField;
        
        private CarServiceAPI.Model.DetaliuComanda DetaliuComandaField;
        
        private byte[] FotoField;
        
        private int ImagineIdField;
        
        private string TitluField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.DetaliuComanda DetaliuComanda
        {
            get
            {
                return this.DetaliuComandaField;
            }
            set
            {
                this.DetaliuComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImagineId
        {
            get
            {
                return this.ImagineIdField;
            }
            set
            {
                this.ImagineIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class DetaliuComanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarServiceAPI.Model.Comanda ComandaField;
        
        private int DetaliuComandaIdField;
        
        private CarServiceAPI.Model.Imagine[] ImaginesField;
        
        private CarServiceAPI.Model.Material[] MaterialsField;
        
        private CarServiceAPI.Model.Mecanic[] MecanicsField;
        
        private CarServiceAPI.Model.Operatie[] OperatiesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Comanda Comanda
        {
            get
            {
                return this.ComandaField;
            }
            set
            {
                this.ComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetaliuComandaId
        {
            get
            {
                return this.DetaliuComandaIdField;
            }
            set
            {
                this.DetaliuComandaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Imagine[] Imagines
        {
            get
            {
                return this.ImaginesField;
            }
            set
            {
                this.ImaginesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Material[] Materials
        {
            get
            {
                return this.MaterialsField;
            }
            set
            {
                this.MaterialsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Mecanic[] Mecanics
        {
            get
            {
                return this.MecanicsField;
            }
            set
            {
                this.MecanicsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarServiceAPI.Model.Operatie[] Operaties
        {
            get
            {
                return this.OperatiesField;
            }
            set
            {
                this.OperatiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CantitateField;
        
        private System.DateTime DataAprovizionareField;
        
        private string DenumireField;
        
        private int MaterialIdField;
        
        private decimal PretField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate
        {
            get
            {
                return this.CantitateField;
            }
            set
            {
                this.CantitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAprovizionare
        {
            get
            {
                return this.DataAprovizionareField;
            }
            set
            {
                this.DataAprovizionareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaterialId
        {
            get
            {
                return this.MaterialIdField;
            }
            set
            {
                this.MaterialIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret
        {
            get
            {
                return this.PretField;
            }
            set
            {
                this.PretField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Mecanic : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MecanicIdField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MecanicId
        {
            get
            {
                return this.MecanicIdField;
            }
            set
            {
                this.MecanicIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/CarServiceAPI.Model", IsReference=true)]
    public partial class Operatie : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DenumireField;
        
        private int OperatieIdField;
        
        private decimal TimpDeExecutieField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperatieId
        {
            get
            {
                return this.OperatieIdField;
            }
            set
            {
                this.OperatieIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimpDeExecutie
        {
            get
            {
                return this.TimpDeExecutieField;
            }
            set
            {
                this.TimpDeExecutieField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICarService")]
public interface ICarService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/AddClient", ReplyAction="http://tempuri.org/InterfaceClient/AddClientResponse")]
    void AddClient(CarServiceAPI.Model.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/AddClient", ReplyAction="http://tempuri.org/InterfaceClient/AddClientResponse")]
    System.Threading.Tasks.Task AddClientAsync(CarServiceAPI.Model.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/UpdateClient", ReplyAction="http://tempuri.org/InterfaceClient/UpdateClientResponse")]
    void UpdateClient(CarServiceAPI.Model.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/UpdateClient", ReplyAction="http://tempuri.org/InterfaceClient/UpdateClientResponse")]
    System.Threading.Tasks.Task UpdateClientAsync(CarServiceAPI.Model.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/DeleteClient", ReplyAction="http://tempuri.org/InterfaceClient/DeleteClientResponse")]
    void DeleteClient(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/DeleteClient", ReplyAction="http://tempuri.org/InterfaceClient/DeleteClientResponse")]
    System.Threading.Tasks.Task DeleteClientAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClients", ReplyAction="http://tempuri.org/InterfaceClient/GetClientsResponse")]
    CarServiceAPI.Model.Client[] GetClients();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClients", ReplyAction="http://tempuri.org/InterfaceClient/GetClientsResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Client[]> GetClientsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientById", ReplyAction="http://tempuri.org/InterfaceClient/GetClientByIdResponse")]
    CarServiceAPI.Model.Client GetClientById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientById", ReplyAction="http://tempuri.org/InterfaceClient/GetClientByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Client> GetClientByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientByAutoId", ReplyAction="http://tempuri.org/InterfaceClient/GetClientByAutoIdResponse")]
    CarServiceAPI.Model.Client GetClientByAutoId(int autoId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientByAutoId", ReplyAction="http://tempuri.org/InterfaceClient/GetClientByAutoIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Client> GetClientByAutoIdAsync(int autoId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/AddAuto", ReplyAction="http://tempuri.org/InterfaceAuto/AddAutoResponse")]
    void AddAuto(CarServiceAPI.Model.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/AddAuto", ReplyAction="http://tempuri.org/InterfaceAuto/AddAutoResponse")]
    System.Threading.Tasks.Task AddAutoAsync(CarServiceAPI.Model.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/UpdateAuto", ReplyAction="http://tempuri.org/InterfaceAuto/UpdateAutoResponse")]
    void UpdateAuto(CarServiceAPI.Model.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/UpdateAuto", ReplyAction="http://tempuri.org/InterfaceAuto/UpdateAutoResponse")]
    System.Threading.Tasks.Task UpdateAutoAsync(CarServiceAPI.Model.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/DeleteAuto", ReplyAction="http://tempuri.org/InterfaceAuto/DeleteAutoResponse")]
    void DeleteAuto(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/DeleteAuto", ReplyAction="http://tempuri.org/InterfaceAuto/DeleteAutoResponse")]
    System.Threading.Tasks.Task DeleteAutoAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoes", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoesResponse")]
    CarServiceAPI.Model.Auto[] GetAutoes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoes", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoesResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Auto[]> GetAutoesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoById", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoByIdResponse")]
    CarServiceAPI.Model.Auto GetAutoById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoById", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Auto> GetAutoByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoesBySasiuId", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoesBySasiuIdResponse")]
    CarServiceAPI.Model.Auto[] GetAutoesBySasiuId(int sasiuId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoesBySasiuId", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoesBySasiuIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Auto[]> GetAutoesBySasiuIdAsync(int sasiuId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComanda", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaResponse")]
    void AddComanda(CarServiceAPI.Model.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComanda", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaResponse")]
    System.Threading.Tasks.Task AddComandaAsync(CarServiceAPI.Model.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/UpdateComanda", ReplyAction="http://tempuri.org/InterfaceComanda/UpdateComandaResponse")]
    void UpdateComanda(CarServiceAPI.Model.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/UpdateComanda", ReplyAction="http://tempuri.org/InterfaceComanda/UpdateComandaResponse")]
    System.Threading.Tasks.Task UpdateComandaAsync(CarServiceAPI.Model.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/DeleteComanda", ReplyAction="http://tempuri.org/InterfaceComanda/DeleteComandaResponse")]
    void DeleteComanda(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/DeleteComanda", ReplyAction="http://tempuri.org/InterfaceComanda/DeleteComandaResponse")]
    System.Threading.Tasks.Task DeleteComandaAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandas", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Client))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Auto[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Auto))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Sasiu))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Client[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Comanda))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Stare))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Comanda[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Imagine[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Imagine))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.DetaliuComanda))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Material[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Material))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Mecanic[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Mecanic))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Operatie[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Operatie))]
    object GetComandas();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandas", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasResponse")]
    System.Threading.Tasks.Task<object> GetComandasAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandaById", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandaByIdResponse")]
    CarServiceAPI.Model.Comanda GetComandaById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandaById", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandaByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda> GetComandaByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByClientId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByClientIdResponse")]
    CarServiceAPI.Model.Comanda[] GetComandasByClientId(int clientId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByClientId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByClientIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByClientIdAsync(int clientId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByAutoId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByAutoIdResponse")]
    CarServiceAPI.Model.Comanda[] GetComandasByAutoId(int autoId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByAutoId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByAutoIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByAutoIdAsync(int autoId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByStare", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByStareResponse")]
    CarServiceAPI.Model.Comanda[] GetComandasByStare(CarServiceAPI.Model.Stare stare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByStare", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByStareResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByStareAsync(CarServiceAPI.Model.Stare stare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByMecanicId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByMecanicIdResponse")]
    CarServiceAPI.Model.Comanda[] GetComandasByMecanicId(int mecanicId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByMecanicId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByMecanicIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByMecanicIdAsync(int mecanicId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByOperatieId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByOperatieIdResponse")]
    CarServiceAPI.Model.Comanda[] GetComandasByOperatieId(int operatieId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByOperatieId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByOperatieIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByOperatieIdAsync(int operatieId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByMaterialId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByMaterialIdResponse")]
    CarServiceAPI.Model.Comanda[] GetComandasByMaterialId(int materialId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandasByMaterialId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandasByMaterialIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByMaterialIdAsync(int materialId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandaByImagineId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandaByImagineIdResponse")]
    CarServiceAPI.Model.Comanda GetComandaByImagineId(int imagineId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetComandaByImagineId", ReplyAction="http://tempuri.org/InterfaceComanda/GetComandaByImagineIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda> GetComandaByImagineIdAsync(int imagineId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetImaginesByComandaId", ReplyAction="http://tempuri.org/InterfaceComanda/GetImaginesByComandaIdResponse")]
    CarServiceAPI.Model.Imagine[] GetImaginesByComandaId(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetImaginesByComandaId", ReplyAction="http://tempuri.org/InterfaceComanda/GetImaginesByComandaIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Imagine[]> GetImaginesByComandaIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComandaMecanic", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaMecanicResponse")]
    void AddComandaMecanic(int id, CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComandaMecanic", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaMecanicResponse")]
    System.Threading.Tasks.Task AddComandaMecanicAsync(int id, CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComandaMaterial", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaMaterialResponse")]
    void AddComandaMaterial(int id, CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComandaMaterial", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaMaterialResponse")]
    System.Threading.Tasks.Task AddComandaMaterialAsync(int id, CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComandaOperatie", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaOperatieResponse")]
    void AddComandaOperatie(int id, CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddComandaOperatie", ReplyAction="http://tempuri.org/InterfaceComanda/AddComandaOperatieResponse")]
    System.Threading.Tasks.Task AddComandaOperatieAsync(int id, CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveComandaMecanic", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveComandaMecanicResponse")]
    void RemoveComandaMecanic(int id, CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveComandaMecanic", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveComandaMecanicResponse")]
    System.Threading.Tasks.Task RemoveComandaMecanicAsync(int id, CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveComandaMaterial", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveComandaMaterialResponse")]
    void RemoveComandaMaterial(int id, CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveComandaMaterial", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveComandaMaterialResponse")]
    System.Threading.Tasks.Task RemoveComandaMaterialAsync(int id, CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveComandaOperatie", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveComandaOperatieResponse")]
    void RemoveComandaOperatie(int id, CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveComandaOperatie", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveComandaOperatieResponse")]
    System.Threading.Tasks.Task RemoveComandaOperatieAsync(int id, CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/AddImagine", ReplyAction="http://tempuri.org/InterfaceImagine/AddImagineResponse")]
    void AddImagine(CarServiceAPI.Model.Imagine imagine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/AddImagine", ReplyAction="http://tempuri.org/InterfaceImagine/AddImagineResponse")]
    System.Threading.Tasks.Task AddImagineAsync(CarServiceAPI.Model.Imagine imagine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/UpdateImagine", ReplyAction="http://tempuri.org/InterfaceImagine/UpdateImagineResponse")]
    void UpdateImagine(CarServiceAPI.Model.Imagine imagine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/UpdateImagine", ReplyAction="http://tempuri.org/InterfaceImagine/UpdateImagineResponse")]
    System.Threading.Tasks.Task UpdateImagineAsync(CarServiceAPI.Model.Imagine imagine);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/DeleteImagine", ReplyAction="http://tempuri.org/InterfaceImagine/DeleteImagineResponse")]
    void DeleteImagine(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/DeleteImagine", ReplyAction="http://tempuri.org/InterfaceImagine/DeleteImagineResponse")]
    System.Threading.Tasks.Task DeleteImagineAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetImagines", ReplyAction="http://tempuri.org/InterfaceImagine/GetImaginesResponse")]
    CarServiceAPI.Model.Imagine[] GetImagines();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetImagines", ReplyAction="http://tempuri.org/InterfaceImagine/GetImaginesResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Imagine[]> GetImaginesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetImagineById", ReplyAction="http://tempuri.org/InterfaceImagine/GetImagineByIdResponse")]
    CarServiceAPI.Model.Imagine GetImagineById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImagine/GetImagineById", ReplyAction="http://tempuri.org/InterfaceImagine/GetImagineByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Imagine> GetImagineByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/AddSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/AddSasiuResponse")]
    void AddSasiu(CarServiceAPI.Model.Sasiu sasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/AddSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/AddSasiuResponse")]
    System.Threading.Tasks.Task AddSasiuAsync(CarServiceAPI.Model.Sasiu sasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/UpdateSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/UpdateSasiuResponse")]
    void UpdateSasiu(CarServiceAPI.Model.Sasiu sasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/UpdateSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/UpdateSasiuResponse")]
    System.Threading.Tasks.Task UpdateSasiuAsync(CarServiceAPI.Model.Sasiu sasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/DeleteSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/DeleteSasiuResponse")]
    void DeleteSasiu(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/DeleteSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/DeleteSasiuResponse")]
    System.Threading.Tasks.Task DeleteSasiuAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasius", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiusResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Client))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Auto[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Auto))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Sasiu))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Client[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Comanda))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Stare))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Comanda[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Imagine[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Imagine))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.DetaliuComanda))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Material[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Material))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Mecanic[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Mecanic))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Operatie[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CarServiceAPI.Model.Operatie))]
    object GetSasius();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasius", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiusResponse")]
    System.Threading.Tasks.Task<object> GetSasiusAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiuById", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuByIdResponse")]
    CarServiceAPI.Model.Sasiu GetSasiuById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiuById", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Sasiu> GetSasiuByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/AddMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/AddMaterialResponse")]
    void AddMaterial(CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/AddMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/AddMaterialResponse")]
    System.Threading.Tasks.Task AddMaterialAsync(CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/UpdateMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/UpdateMaterialResponse")]
    void UpdateMaterial(CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/UpdateMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/UpdateMaterialResponse")]
    System.Threading.Tasks.Task UpdateMaterialAsync(CarServiceAPI.Model.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/DeleteMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/DeleteMaterialResponse")]
    void DeleteMaterial(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/DeleteMaterial", ReplyAction="http://tempuri.org/InterfaceMaterial/DeleteMaterialResponse")]
    System.Threading.Tasks.Task DeleteMaterialAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetMaterials", ReplyAction="http://tempuri.org/InterfaceMaterial/GetMaterialsResponse")]
    CarServiceAPI.Model.Material[] GetMaterials();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetMaterials", ReplyAction="http://tempuri.org/InterfaceMaterial/GetMaterialsResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Material[]> GetMaterialsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetMaterialById", ReplyAction="http://tempuri.org/InterfaceMaterial/GetMaterialByIdResponse")]
    CarServiceAPI.Model.Material GetMaterialById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMaterial/GetMaterialById", ReplyAction="http://tempuri.org/InterfaceMaterial/GetMaterialByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Material> GetMaterialByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/AddMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/AddMecanicResponse")]
    void AddMecanic(CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/AddMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/AddMecanicResponse")]
    System.Threading.Tasks.Task AddMecanicAsync(CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/UpdateMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/UpdateMecanicResponse")]
    void UpdateMecanic(CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/UpdateMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/UpdateMecanicResponse")]
    System.Threading.Tasks.Task UpdateMecanicAsync(CarServiceAPI.Model.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/DeleteMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/DeleteMecanicResponse")]
    void DeleteMecanic(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/DeleteMecanic", ReplyAction="http://tempuri.org/InterfaceMecanic/DeleteMecanicResponse")]
    System.Threading.Tasks.Task DeleteMecanicAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetMecanics", ReplyAction="http://tempuri.org/InterfaceMecanic/GetMecanicsResponse")]
    CarServiceAPI.Model.Mecanic[] GetMecanics();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetMecanics", ReplyAction="http://tempuri.org/InterfaceMecanic/GetMecanicsResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Mecanic[]> GetMecanicsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetMecanicById", ReplyAction="http://tempuri.org/InterfaceMecanic/GetMecanicByIdResponse")]
    CarServiceAPI.Model.Mecanic GetMecanicById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceMecanic/GetMecanicById", ReplyAction="http://tempuri.org/InterfaceMecanic/GetMecanicByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Mecanic> GetMecanicByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/AddOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/AddOperatieResponse")]
    void AddOperatie(CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/AddOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/AddOperatieResponse")]
    System.Threading.Tasks.Task AddOperatieAsync(CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/UpdateOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/UpdateOperatieResponse")]
    void UpdateOperatie(CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/UpdateOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/UpdateOperatieResponse")]
    System.Threading.Tasks.Task UpdateOperatieAsync(CarServiceAPI.Model.Operatie operatie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/DeleteOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/DeleteOperatieResponse")]
    void DeleteOperatie(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/DeleteOperatie", ReplyAction="http://tempuri.org/InterfaceOperatie/DeleteOperatieResponse")]
    System.Threading.Tasks.Task DeleteOperatieAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetOperaties", ReplyAction="http://tempuri.org/InterfaceOperatie/GetOperatiesResponse")]
    CarServiceAPI.Model.Operatie[] GetOperaties();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetOperaties", ReplyAction="http://tempuri.org/InterfaceOperatie/GetOperatiesResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Operatie[]> GetOperatiesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetOperatieById", ReplyAction="http://tempuri.org/InterfaceOperatie/GetOperatieByIdResponse")]
    CarServiceAPI.Model.Operatie GetOperatieById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceOperatie/GetOperatieById", ReplyAction="http://tempuri.org/InterfaceOperatie/GetOperatieByIdResponse")]
    System.Threading.Tasks.Task<CarServiceAPI.Model.Operatie> GetOperatieByIdAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICarServiceChannel : ICarService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CarServiceClient : System.ServiceModel.ClientBase<ICarService>, ICarService
{
    
    public CarServiceClient()
    {
    }
    
    public CarServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddClient(CarServiceAPI.Model.Client client)
    {
        base.Channel.AddClient(client);
    }
    
    public System.Threading.Tasks.Task AddClientAsync(CarServiceAPI.Model.Client client)
    {
        return base.Channel.AddClientAsync(client);
    }
    
    public void UpdateClient(CarServiceAPI.Model.Client client)
    {
        base.Channel.UpdateClient(client);
    }
    
    public System.Threading.Tasks.Task UpdateClientAsync(CarServiceAPI.Model.Client client)
    {
        return base.Channel.UpdateClientAsync(client);
    }
    
    public void DeleteClient(int id)
    {
        base.Channel.DeleteClient(id);
    }
    
    public System.Threading.Tasks.Task DeleteClientAsync(int id)
    {
        return base.Channel.DeleteClientAsync(id);
    }
    
    public CarServiceAPI.Model.Client[] GetClients()
    {
        return base.Channel.GetClients();
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Client[]> GetClientsAsync()
    {
        return base.Channel.GetClientsAsync();
    }
    
    public CarServiceAPI.Model.Client GetClientById(int id)
    {
        return base.Channel.GetClientById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Client> GetClientByIdAsync(int id)
    {
        return base.Channel.GetClientByIdAsync(id);
    }
    
    public CarServiceAPI.Model.Client GetClientByAutoId(int autoId)
    {
        return base.Channel.GetClientByAutoId(autoId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Client> GetClientByAutoIdAsync(int autoId)
    {
        return base.Channel.GetClientByAutoIdAsync(autoId);
    }
    
    public void AddAuto(CarServiceAPI.Model.Auto auto)
    {
        base.Channel.AddAuto(auto);
    }
    
    public System.Threading.Tasks.Task AddAutoAsync(CarServiceAPI.Model.Auto auto)
    {
        return base.Channel.AddAutoAsync(auto);
    }
    
    public void UpdateAuto(CarServiceAPI.Model.Auto auto)
    {
        base.Channel.UpdateAuto(auto);
    }
    
    public System.Threading.Tasks.Task UpdateAutoAsync(CarServiceAPI.Model.Auto auto)
    {
        return base.Channel.UpdateAutoAsync(auto);
    }
    
    public void DeleteAuto(int id)
    {
        base.Channel.DeleteAuto(id);
    }
    
    public System.Threading.Tasks.Task DeleteAutoAsync(int id)
    {
        return base.Channel.DeleteAutoAsync(id);
    }
    
    public CarServiceAPI.Model.Auto[] GetAutoes()
    {
        return base.Channel.GetAutoes();
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Auto[]> GetAutoesAsync()
    {
        return base.Channel.GetAutoesAsync();
    }
    
    public CarServiceAPI.Model.Auto GetAutoById(int id)
    {
        return base.Channel.GetAutoById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Auto> GetAutoByIdAsync(int id)
    {
        return base.Channel.GetAutoByIdAsync(id);
    }
    
    public CarServiceAPI.Model.Auto[] GetAutoesBySasiuId(int sasiuId)
    {
        return base.Channel.GetAutoesBySasiuId(sasiuId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Auto[]> GetAutoesBySasiuIdAsync(int sasiuId)
    {
        return base.Channel.GetAutoesBySasiuIdAsync(sasiuId);
    }
    
    public void AddComanda(CarServiceAPI.Model.Comanda comanda)
    {
        base.Channel.AddComanda(comanda);
    }
    
    public System.Threading.Tasks.Task AddComandaAsync(CarServiceAPI.Model.Comanda comanda)
    {
        return base.Channel.AddComandaAsync(comanda);
    }
    
    public void UpdateComanda(CarServiceAPI.Model.Comanda comanda)
    {
        base.Channel.UpdateComanda(comanda);
    }
    
    public System.Threading.Tasks.Task UpdateComandaAsync(CarServiceAPI.Model.Comanda comanda)
    {
        return base.Channel.UpdateComandaAsync(comanda);
    }
    
    public void DeleteComanda(int id)
    {
        base.Channel.DeleteComanda(id);
    }
    
    public System.Threading.Tasks.Task DeleteComandaAsync(int id)
    {
        return base.Channel.DeleteComandaAsync(id);
    }
    
    public object GetComandas()
    {
        return base.Channel.GetComandas();
    }
    
    public System.Threading.Tasks.Task<object> GetComandasAsync()
    {
        return base.Channel.GetComandasAsync();
    }
    
    public CarServiceAPI.Model.Comanda GetComandaById(int id)
    {
        return base.Channel.GetComandaById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda> GetComandaByIdAsync(int id)
    {
        return base.Channel.GetComandaByIdAsync(id);
    }
    
    public CarServiceAPI.Model.Comanda[] GetComandasByClientId(int clientId)
    {
        return base.Channel.GetComandasByClientId(clientId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByClientIdAsync(int clientId)
    {
        return base.Channel.GetComandasByClientIdAsync(clientId);
    }
    
    public CarServiceAPI.Model.Comanda[] GetComandasByAutoId(int autoId)
    {
        return base.Channel.GetComandasByAutoId(autoId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByAutoIdAsync(int autoId)
    {
        return base.Channel.GetComandasByAutoIdAsync(autoId);
    }
    
    public CarServiceAPI.Model.Comanda[] GetComandasByStare(CarServiceAPI.Model.Stare stare)
    {
        return base.Channel.GetComandasByStare(stare);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByStareAsync(CarServiceAPI.Model.Stare stare)
    {
        return base.Channel.GetComandasByStareAsync(stare);
    }
    
    public CarServiceAPI.Model.Comanda[] GetComandasByMecanicId(int mecanicId)
    {
        return base.Channel.GetComandasByMecanicId(mecanicId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByMecanicIdAsync(int mecanicId)
    {
        return base.Channel.GetComandasByMecanicIdAsync(mecanicId);
    }
    
    public CarServiceAPI.Model.Comanda[] GetComandasByOperatieId(int operatieId)
    {
        return base.Channel.GetComandasByOperatieId(operatieId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByOperatieIdAsync(int operatieId)
    {
        return base.Channel.GetComandasByOperatieIdAsync(operatieId);
    }
    
    public CarServiceAPI.Model.Comanda[] GetComandasByMaterialId(int materialId)
    {
        return base.Channel.GetComandasByMaterialId(materialId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda[]> GetComandasByMaterialIdAsync(int materialId)
    {
        return base.Channel.GetComandasByMaterialIdAsync(materialId);
    }
    
    public CarServiceAPI.Model.Comanda GetComandaByImagineId(int imagineId)
    {
        return base.Channel.GetComandaByImagineId(imagineId);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Comanda> GetComandaByImagineIdAsync(int imagineId)
    {
        return base.Channel.GetComandaByImagineIdAsync(imagineId);
    }
    
    public CarServiceAPI.Model.Imagine[] GetImaginesByComandaId(int id)
    {
        return base.Channel.GetImaginesByComandaId(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Imagine[]> GetImaginesByComandaIdAsync(int id)
    {
        return base.Channel.GetImaginesByComandaIdAsync(id);
    }
    
    public void AddComandaMecanic(int id, CarServiceAPI.Model.Mecanic mecanic)
    {
        base.Channel.AddComandaMecanic(id, mecanic);
    }
    
    public System.Threading.Tasks.Task AddComandaMecanicAsync(int id, CarServiceAPI.Model.Mecanic mecanic)
    {
        return base.Channel.AddComandaMecanicAsync(id, mecanic);
    }
    
    public void AddComandaMaterial(int id, CarServiceAPI.Model.Material material)
    {
        base.Channel.AddComandaMaterial(id, material);
    }
    
    public System.Threading.Tasks.Task AddComandaMaterialAsync(int id, CarServiceAPI.Model.Material material)
    {
        return base.Channel.AddComandaMaterialAsync(id, material);
    }
    
    public void AddComandaOperatie(int id, CarServiceAPI.Model.Operatie operatie)
    {
        base.Channel.AddComandaOperatie(id, operatie);
    }
    
    public System.Threading.Tasks.Task AddComandaOperatieAsync(int id, CarServiceAPI.Model.Operatie operatie)
    {
        return base.Channel.AddComandaOperatieAsync(id, operatie);
    }
    
    public void RemoveComandaMecanic(int id, CarServiceAPI.Model.Mecanic mecanic)
    {
        base.Channel.RemoveComandaMecanic(id, mecanic);
    }
    
    public System.Threading.Tasks.Task RemoveComandaMecanicAsync(int id, CarServiceAPI.Model.Mecanic mecanic)
    {
        return base.Channel.RemoveComandaMecanicAsync(id, mecanic);
    }
    
    public void RemoveComandaMaterial(int id, CarServiceAPI.Model.Material material)
    {
        base.Channel.RemoveComandaMaterial(id, material);
    }
    
    public System.Threading.Tasks.Task RemoveComandaMaterialAsync(int id, CarServiceAPI.Model.Material material)
    {
        return base.Channel.RemoveComandaMaterialAsync(id, material);
    }
    
    public void RemoveComandaOperatie(int id, CarServiceAPI.Model.Operatie operatie)
    {
        base.Channel.RemoveComandaOperatie(id, operatie);
    }
    
    public System.Threading.Tasks.Task RemoveComandaOperatieAsync(int id, CarServiceAPI.Model.Operatie operatie)
    {
        return base.Channel.RemoveComandaOperatieAsync(id, operatie);
    }
    
    public void AddImagine(CarServiceAPI.Model.Imagine imagine)
    {
        base.Channel.AddImagine(imagine);
    }
    
    public System.Threading.Tasks.Task AddImagineAsync(CarServiceAPI.Model.Imagine imagine)
    {
        return base.Channel.AddImagineAsync(imagine);
    }
    
    public void UpdateImagine(CarServiceAPI.Model.Imagine imagine)
    {
        base.Channel.UpdateImagine(imagine);
    }
    
    public System.Threading.Tasks.Task UpdateImagineAsync(CarServiceAPI.Model.Imagine imagine)
    {
        return base.Channel.UpdateImagineAsync(imagine);
    }
    
    public void DeleteImagine(int id)
    {
        base.Channel.DeleteImagine(id);
    }
    
    public System.Threading.Tasks.Task DeleteImagineAsync(int id)
    {
        return base.Channel.DeleteImagineAsync(id);
    }
    
    public CarServiceAPI.Model.Imagine[] GetImagines()
    {
        return base.Channel.GetImagines();
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Imagine[]> GetImaginesAsync()
    {
        return base.Channel.GetImaginesAsync();
    }
    
    public CarServiceAPI.Model.Imagine GetImagineById(int id)
    {
        return base.Channel.GetImagineById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Imagine> GetImagineByIdAsync(int id)
    {
        return base.Channel.GetImagineByIdAsync(id);
    }
    
    public void AddSasiu(CarServiceAPI.Model.Sasiu sasiu)
    {
        base.Channel.AddSasiu(sasiu);
    }
    
    public System.Threading.Tasks.Task AddSasiuAsync(CarServiceAPI.Model.Sasiu sasiu)
    {
        return base.Channel.AddSasiuAsync(sasiu);
    }
    
    public void UpdateSasiu(CarServiceAPI.Model.Sasiu sasiu)
    {
        base.Channel.UpdateSasiu(sasiu);
    }
    
    public System.Threading.Tasks.Task UpdateSasiuAsync(CarServiceAPI.Model.Sasiu sasiu)
    {
        return base.Channel.UpdateSasiuAsync(sasiu);
    }
    
    public void DeleteSasiu(int id)
    {
        base.Channel.DeleteSasiu(id);
    }
    
    public System.Threading.Tasks.Task DeleteSasiuAsync(int id)
    {
        return base.Channel.DeleteSasiuAsync(id);
    }
    
    public object GetSasius()
    {
        return base.Channel.GetSasius();
    }
    
    public System.Threading.Tasks.Task<object> GetSasiusAsync()
    {
        return base.Channel.GetSasiusAsync();
    }
    
    public CarServiceAPI.Model.Sasiu GetSasiuById(int id)
    {
        return base.Channel.GetSasiuById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Sasiu> GetSasiuByIdAsync(int id)
    {
        return base.Channel.GetSasiuByIdAsync(id);
    }
    
    public void AddMaterial(CarServiceAPI.Model.Material material)
    {
        base.Channel.AddMaterial(material);
    }
    
    public System.Threading.Tasks.Task AddMaterialAsync(CarServiceAPI.Model.Material material)
    {
        return base.Channel.AddMaterialAsync(material);
    }
    
    public void UpdateMaterial(CarServiceAPI.Model.Material material)
    {
        base.Channel.UpdateMaterial(material);
    }
    
    public System.Threading.Tasks.Task UpdateMaterialAsync(CarServiceAPI.Model.Material material)
    {
        return base.Channel.UpdateMaterialAsync(material);
    }
    
    public void DeleteMaterial(int id)
    {
        base.Channel.DeleteMaterial(id);
    }
    
    public System.Threading.Tasks.Task DeleteMaterialAsync(int id)
    {
        return base.Channel.DeleteMaterialAsync(id);
    }
    
    public CarServiceAPI.Model.Material[] GetMaterials()
    {
        return base.Channel.GetMaterials();
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Material[]> GetMaterialsAsync()
    {
        return base.Channel.GetMaterialsAsync();
    }
    
    public CarServiceAPI.Model.Material GetMaterialById(int id)
    {
        return base.Channel.GetMaterialById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Material> GetMaterialByIdAsync(int id)
    {
        return base.Channel.GetMaterialByIdAsync(id);
    }
    
    public void AddMecanic(CarServiceAPI.Model.Mecanic mecanic)
    {
        base.Channel.AddMecanic(mecanic);
    }
    
    public System.Threading.Tasks.Task AddMecanicAsync(CarServiceAPI.Model.Mecanic mecanic)
    {
        return base.Channel.AddMecanicAsync(mecanic);
    }
    
    public void UpdateMecanic(CarServiceAPI.Model.Mecanic mecanic)
    {
        base.Channel.UpdateMecanic(mecanic);
    }
    
    public System.Threading.Tasks.Task UpdateMecanicAsync(CarServiceAPI.Model.Mecanic mecanic)
    {
        return base.Channel.UpdateMecanicAsync(mecanic);
    }
    
    public void DeleteMecanic(int id)
    {
        base.Channel.DeleteMecanic(id);
    }
    
    public System.Threading.Tasks.Task DeleteMecanicAsync(int id)
    {
        return base.Channel.DeleteMecanicAsync(id);
    }
    
    public CarServiceAPI.Model.Mecanic[] GetMecanics()
    {
        return base.Channel.GetMecanics();
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Mecanic[]> GetMecanicsAsync()
    {
        return base.Channel.GetMecanicsAsync();
    }
    
    public CarServiceAPI.Model.Mecanic GetMecanicById(int id)
    {
        return base.Channel.GetMecanicById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Mecanic> GetMecanicByIdAsync(int id)
    {
        return base.Channel.GetMecanicByIdAsync(id);
    }
    
    public void AddOperatie(CarServiceAPI.Model.Operatie operatie)
    {
        base.Channel.AddOperatie(operatie);
    }
    
    public System.Threading.Tasks.Task AddOperatieAsync(CarServiceAPI.Model.Operatie operatie)
    {
        return base.Channel.AddOperatieAsync(operatie);
    }
    
    public void UpdateOperatie(CarServiceAPI.Model.Operatie operatie)
    {
        base.Channel.UpdateOperatie(operatie);
    }
    
    public System.Threading.Tasks.Task UpdateOperatieAsync(CarServiceAPI.Model.Operatie operatie)
    {
        return base.Channel.UpdateOperatieAsync(operatie);
    }
    
    public void DeleteOperatie(int id)
    {
        base.Channel.DeleteOperatie(id);
    }
    
    public System.Threading.Tasks.Task DeleteOperatieAsync(int id)
    {
        return base.Channel.DeleteOperatieAsync(id);
    }
    
    public CarServiceAPI.Model.Operatie[] GetOperaties()
    {
        return base.Channel.GetOperaties();
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Operatie[]> GetOperatiesAsync()
    {
        return base.Channel.GetOperatiesAsync();
    }
    
    public CarServiceAPI.Model.Operatie GetOperatieById(int id)
    {
        return base.Channel.GetOperatieById(id);
    }
    
    public System.Threading.Tasks.Task<CarServiceAPI.Model.Operatie> GetOperatieByIdAsync(int id)
    {
        return base.Channel.GetOperatieByIdAsync(id);
    }
}
